import { DEFAULT_PROJECT_ICON, PROJECT_ICONS, type ProjectIconName } from "@rudderhq/shared";
import {
  BadgeDollarSign,
  BookOpen,
  Braces,
  Brain,
  BriefcaseBusiness,
  Calendar,
  ChartNoAxesColumnIncreasing,
  Clover,
  Code,
  Database,
  Dumbbell,
  FlaskConical,
  Flower2,
  Folder,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Lightbulb,
  Megaphone,
  Music,
  NotebookTabs,
  Package,
  Paintbrush,
  Palette,
  PawPrint,
  PenTool,
  Pencil,
  Plane,
  Popcorn,
  Rocket,
  Scale,
  Shield,
  SquareTerminal,
  Stethoscope,
  Target,
  TreePalm,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const projectIconValues = new Set<string>(PROJECT_ICONS);

export const PROJECT_ICON_COMPONENTS: Record<ProjectIconName, LucideIcon> = {
  folder: Folder,
  dollar: BadgeDollarSign,
  book: BookOpen,
  "graduation-cap": GraduationCap,
  pencil: Pencil,
  "pen-tool": PenTool,
  braces: Braces,
  terminal: SquareTerminal,
  music: Music,
  popcorn: Popcorn,
  paintbrush: Paintbrush,
  palette: Palette,
  stethoscope: Stethoscope,
  clover: Clover,
  flower: Flower2,
  briefcase: BriefcaseBusiness,
  chart: ChartNoAxesColumnIncreasing,
  database: Database,
  dumbbell: Dumbbell,
  notebook: NotebookTabs,
  scale: Scale,
  plane: Plane,
  globe: Globe,
  home: Home,
  "tree-palm": TreePalm,
  heart: Heart,
  gift: Gift,
  wrench: Wrench,
  "paw-print": PawPrint,
  flask: FlaskConical,
  brain: Brain,
  code: Code,
  rocket: Rocket,
  target: Target,
  lightbulb: Lightbulb,
  shield: Shield,
  megaphone: Megaphone,
  users: Users,
  calendar: Calendar,
  package: Package,
};

export function normalizeProjectIconName(icon: string | null | undefined): ProjectIconName {
  const normalized = icon?.trim().toLowerCase();
  return projectIconValues.has(normalized ?? "") ? (normalized as ProjectIconName) : DEFAULT_PROJECT_ICON;
}

export function getProjectIconComponent(icon: string | null | undefined): LucideIcon {
  return PROJECT_ICON_COMPONENTS[normalizeProjectIconName(icon)];
}
