import type { Approval } from "./approval.js";
import type { ChatConversationMutability } from "../constants.js";

export interface ChatLinkedEntity {
  type: "issue" | "project" | "agent";
  id: string;
  label: string;
  subtitle: string | null;
  identifier: string | null;
  status: string | null;
  description?: string | null;
  priority?: string | null;
  href: string;
}

export interface ChatContextLink {
  id: string;
  orgId: string;
  conversationId: string;
  entityType: "issue" | "project" | "agent";
  entityId: string;
  metadata: Record<string, unknown> | null;
  entity: ChatLinkedEntity | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ChatAttachment {
  id: string;
  orgId: string;
  conversationId: string;
  messageId: string;
  assetId: string;
  provider: string;
  objectKey: string;
  contentType: string;
  byteSize: number;
  sha256: string;
  originalFilename: string | null;
  createdByAgentId: string | null;
  createdByUserId: string | null;
  createdAt: Date;
  updatedAt: Date;
  contentPath: string;
}

export interface ChatPrimaryIssueSummary {
  id: string;
  identifier: string | null;
  title: string;
  status: string;
  priority: string;
}

export interface ChatRuntimeDescriptor {
  sourceType: "agent" | "unconfigured";
  sourceLabel: string;
  runtimeAgentId: string | null;
  agentRuntimeType: string | null;
  model: string | null;
  available: boolean;
  error: string | null;
}

export type ChatQueuedMessageStatus =
  | "queued"
  | "steer_pending"
  | "steered"
  | "dequeue_claimed"
  | "running"
  | "completed"
  | "cancelled"
  | "failed";

export type ChatSteerResult =
  | "accepted"
  | "pending"
  | "queued_fallback"
  | "stale_generation"
  | "closing"
  | "unsupported";

export interface ChatQueuedMessagePayload {
  body: string;
  attachmentIds?: string[];
  projectId?: string | null;
  skillRefs?: string[];
  accessMode?: string | null;
  model?: string | null;
  effort?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface ChatQueuedMessage {
  id: string;
  orgId: string;
  conversationId: string;
  position: number;
  status: ChatQueuedMessageStatus;
  version: number;
  clientMutationId: string;
  payload: ChatQueuedMessagePayload;
  expectedGenerationId: string | null;
  activeGenerationId: string | null;
  deliveryAttempts: number;
  lastAttemptAt: Date | null;
  lastDeliveryReason: string | null;
  sourceMessageId: string | null;
  deliveredMessageId: string | null;
  cancelledAt: Date | null;
  steeredAt: Date | null;
  dequeuedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ChatQueueSnapshot {
  activeGenerationId: string | null;
  items: ChatQueuedMessage[];
}

export interface ChatQueueClaimResponse {
  item: ChatQueuedMessage | null;
}

export interface ChatSteerResponse {
  item: ChatQueuedMessage;
  result: ChatSteerResult;
  activeGenerationId: string | null;
  queueVersion: number;
  transcriptEventId: string | null;
}

export interface ChatConversation {
  id: string;
  orgId: string;
  status: "active" | "resolved" | "archived";
  mutability: ChatConversationMutability;
  title: string;
  summary: string | null;
  latestReplyPreview: string | null;
  latestUserMessagePreview: string | null;
  userMessageCount: number;
  searchPreview?: string | null;
  preferredAgentId: string | null;
  routedAgentId: string | null;
  primaryIssueId: string | null;
  forkedFromConversationId: string | null;
  forkedFromMessageId: string | null;
  forkRootConversationId: string | null;
  primaryIssue: ChatPrimaryIssueSummary | null;
  issueCreationMode: "manual_approval" | "auto_create";
  planMode: boolean;
  createdByUserId: string | null;
  lastMessageAt: Date | null;
  lastReadAt: Date | null;
  isPinned: boolean;
  isUnread: boolean;
  unreadCount: number;
  needsAttention: boolean;
  resolvedAt: Date | null;
  contextLinks: ChatContextLink[];
  sourceMetadata?: Record<string, unknown> | null;
  chatRuntime: ChatRuntimeDescriptor;
  createdAt: Date;
  updatedAt: Date;
}

export interface ChatMessage {
  id: string;
  orgId: string;
  conversationId: string;
  role: "user" | "assistant" | "system";
  kind:
    | "message"
    | "ask_user"
    | "issue_proposal"
    | "operation_proposal"
    | "system_event";
  status: "streaming" | "completed" | "stopped" | "failed" | "interrupted";
  body: string;
  structuredPayload: Record<string, unknown> | null;
  approvalId: string | null;
  approval: Approval | null;
  attachments: ChatAttachment[];
  transcript?: ChatStreamTranscriptEntry[];
  transcriptSummary?: ChatTranscriptSummary | null;
  /** Agent run that produced this assistant message, when generated by a real runtime. */
  runId?: string | null;
  /** Agent whose runtime produced this assistant message. */
  replyingAgentId: string | null;
  /** Groups user+assistant rows for one logical turn; new variant on edit/regenerate. */
  chatTurnId: string | null;
  turnVariant: number;
  supersededAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ChatTranscriptSummary {
  entryCount: number;
  startedAt: string | null;
  endedAt: string | null;
}

export type ChatRichReferenceDisplay = "card" | "inline";

export interface ChatAskUserOption {
  id: string;
  label: string;
  description?: string;
  recommended?: boolean;
}

export interface ChatAskUserQuestion {
  id: string;
  header?: string;
  question: string;
  options: ChatAskUserOption[];
  selectionMode?: "single" | "multiple";
  allowFreeform?: boolean;
}

export interface ChatAskUserRequest {
  questions: ChatAskUserQuestion[];
}

export type ChatRichReference =
  | {
    type: "issue";
    issueId?: string;
    identifier?: string;
    display?: ChatRichReferenceDisplay;
  }
  | {
    type: "issue_comment";
    issueId?: string;
    identifier?: string;
    commentId: string;
    display?: ChatRichReferenceDisplay;
  };

export type ChatOperationProposalDecisionAction = "approve" | "reject" | "requestRevision";

export type ChatOperationProposalDecisionStatus =
  | "pending"
  | "approved"
  | "rejected"
  | "revision_requested";

export interface ChatOperationProposalDecision {
  status: ChatOperationProposalDecisionStatus;
  decisionNote: string | null;
  decidedByUserId: string | null;
  decidedAt: string | null;
}

export type ChatStreamTranscriptEntry =
  | { kind: "assistant"; ts: string; text: string; delta?: boolean }
  | { kind: "thinking"; ts: string; text: string; delta?: boolean }
  | { kind: "user"; ts: string; text: string }
  | { kind: "tool_call"; ts: string; name: string; input: unknown; toolUseId?: string }
  | { kind: "tool_result"; ts: string; toolUseId: string; toolName?: string; content: string; isError: boolean }
  | { kind: "todo_list"; ts: string; todoListId?: string; items: ChatStreamTranscriptTodoItem[] }
  | { kind: "init"; ts: string; model: string; sessionId: string }
  | { kind: "result"; ts: string; text: string; inputTokens: number; outputTokens: number; cachedTokens: number; costUsd: number; subtype: string; isError: boolean; errors: string[] }
  | { kind: "stderr"; ts: string; text: string }
  | { kind: "system"; ts: string; text: string }
  | { kind: "stdout"; ts: string; text: string };

export type ChatStreamTranscriptTodoItemStatus = "pending" | "in_progress" | "completed";

export interface ChatStreamTranscriptTodoItem {
  text: string;
  status: ChatStreamTranscriptTodoItemStatus;
}

export interface ChatStreamAckEvent {
  type: "ack";
  userMessage: ChatMessage;
}

export interface ChatStreamAssistantDeltaEvent {
  type: "assistant_delta";
  delta: string;
}

export interface ChatStreamAssistantStateEvent {
  type: "assistant_state";
  state: "streaming" | "finalizing" | "stopped";
}

export interface ChatStreamTranscriptEntryEvent {
  type: "transcript_entry";
  entry: ChatStreamTranscriptEntry;
}

export interface ChatStreamFinalEvent {
  type: "final";
  messages: ChatMessage[];
}

export interface ChatStreamErrorEvent {
  type: "error";
  error: string;
  messageId?: string | null;
}

export interface ChatStreamQueuedEvent {
  type: "queued";
  item: ChatQueuedMessage;
}

export type ChatStreamEvent =
  | ChatStreamAckEvent
  | ChatStreamAssistantDeltaEvent
  | ChatStreamAssistantStateEvent
  | ChatStreamTranscriptEntryEvent
  | ChatStreamFinalEvent
  | ChatStreamErrorEvent
  | ChatStreamQueuedEvent;
